@startuml
title Activity Diagram 

start
:Користувач вводить назву композиції або ім'я автора;
if (Результати пошуку знайдено?) then (Yes)
  :Отримано плейлісти у \n відповідності до запиту;
else (No)
  :Помилка, даних не існує!;
endif
stop

@enduml
