@startuml
title Classes Diagram

Class Користувач
Class "Список композицій"
Class "Інформація про композицію"

"Користувач""*" -> "*""Список композицій" : переглядає
"Список композицій""1" o-- "*""Інформація про композицію"
"Користувач""*" -> "*""Інформація про композицію" : отримує

@enduml
